/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerbd;
//import com.mysql.jdbc.Connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian Enriquez
 */
public class LoginMySQL extends javax.swing.JFrame {

    
    public String url = "jdbc:mysql://localhost:3306/tienda";
    public static String driver = "com.mysql.jdbc.Driver";
    //public String CampoUser = "";
    //public String CampoPass = "";
     
    
    /**
     * Creates new form Login
     */
    public LoginMySQL() {
        initComponents();
        this.setTitle("Login MySQL");
        this.setLocation(400,220);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alumno = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        UserAdmin = new javax.swing.JLabel();
        PassAdmin = new javax.swing.JLabel();
        CampoUserAdmin = new javax.swing.JTextField();
        ConectarAdmin = new javax.swing.JButton();
        Estado = new javax.swing.JLabel();
        PasswordAdmin = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        UserProfesor = new javax.swing.JLabel();
        CampoUserProfesor = new javax.swing.JTextField();
        ConectarProfesor = new javax.swing.JButton();
        PassProfesor = new javax.swing.JLabel();
        PasswordProfesor = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        UserAlumno = new javax.swing.JLabel();
        CampoUserAlumno = new javax.swing.JTextField();
        ConectarAlumno = new javax.swing.JButton();
        PassAlumno = new javax.swing.JLabel();
        PasswordAlumno = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserAdmin.setText("Usuario");

        PassAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassAdmin.setText("Contraseña");

        ConectarAdmin.setText("Conectar");
        ConectarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConectarAdminMouseClicked(evt);
            }
        });
        ConectarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassAdmin))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoUserAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(PasswordAdmin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(ConectarAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassAdmin)
                    .addComponent(PasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ConectarAdmin)
                        .addGap(35, 35, 35))))
        );

        Alumno.addTab("Admin", jPanel1);

        UserProfesor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserProfesor.setText("Usuario");

        ConectarProfesor.setText("Conectar");
        ConectarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConectarProfesorMouseClicked(evt);
            }
        });
        ConectarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarProfesorActionPerformed(evt);
            }
        });

        PassProfesor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassProfesor.setText("Contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassProfesor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoUserProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(PasswordProfesor))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ConectarProfesor)
                        .addGap(62, 266, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoUserProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PassProfesor)
                    .addComponent(PasswordProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ConectarProfesor)
                .addGap(22, 22, 22))
        );

        Alumno.addTab("Gerente", jPanel2);

        UserAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserAlumno.setText("Usuario");

        ConectarAlumno.setText("Conectar");
        ConectarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConectarAlumnoMouseClicked(evt);
            }
        });
        ConectarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarAlumnoActionPerformed(evt);
            }
        });

        PassAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassAlumno.setText("Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassAlumno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoUserAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(PasswordAlumno))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ConectarAlumno)
                        .addGap(62, 266, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoUserAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PassAlumno)
                    .addComponent(PasswordAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ConectarAlumno)
                .addGap(22, 22, 22))
        );

        Alumno.addTab("Empleado", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarAdminActionPerformed
      Connection conexion = null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            conexion = (Connection) DriverManager.getConnection(url, CampoUserAdmin.getText(),PasswordAdmin.getText());               
            }
            // Si la conexion NO fue exitosa mostramos un mensaje de error
            catch (ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this, e);       
            }
        
    }//GEN-LAST:event_ConectarAdminActionPerformed
    
    private void ConectarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarProfesorActionPerformed
       Connection conexion = null;
        try{
            Class.forName(driver);
            
            conexion = (Connection) DriverManager.getConnection(url, CampoUserProfesor.getText(),PasswordProfesor.getText());               
            }
            
            catch (ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this, e);       
            }
    }//GEN-LAST:event_ConectarProfesorActionPerformed
    
    
    
    private void ConectarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarAlumnoActionPerformed
     Connection conexion = null;
        try{
            Class.forName(driver);
            
            conexion = (Connection) DriverManager.getConnection(url, CampoUserAlumno.getText(),PasswordAlumno.getText());               
            }
            
            catch (ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this, e);       
            }
    }//GEN-LAST:event_ConectarAlumnoActionPerformed
   
    
    private void ConectarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarAdminMouseClicked
    OperacionesAdmin opaA = new OperacionesAdmin();
    opaA.setVisible(true);
    dispose();
    }//GEN-LAST:event_ConectarAdminMouseClicked

    private void ConectarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarAlumnoMouseClicked
        
    }//GEN-LAST:event_ConectarAlumnoMouseClicked

    private void ConectarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarProfesorMouseClicked
       
    }//GEN-LAST:event_ConectarProfesorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMySQL().setVisible(true);
            }
        }
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Alumno;
    public javax.swing.JTextField CampoUserAdmin;
    public javax.swing.JTextField CampoUserAlumno;
    public javax.swing.JTextField CampoUserProfesor;
    public javax.swing.JButton ConectarAdmin;
    private javax.swing.JButton ConectarAlumno;
    private javax.swing.JButton ConectarProfesor;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel PassAdmin;
    private javax.swing.JLabel PassAlumno;
    private javax.swing.JLabel PassProfesor;
    public javax.swing.JPasswordField PasswordAdmin;
    public javax.swing.JPasswordField PasswordAlumno;
    public javax.swing.JPasswordField PasswordProfesor;
    private javax.swing.JLabel UserAdmin;
    private javax.swing.JLabel UserAlumno;
    private javax.swing.JLabel UserProfesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
  
}
